name: pull labeler

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    container:
      image: node:lts
    steps:
      - name: Apply labels
        uses: actions/labeler@v5
